# Generated by Django 4.1.3 on 2022-12-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DgmallArticle',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content_desc', models.TextField(blank=True, null=True)),
                ('is_active', models.SmallIntegerField(default=0)),
                ('image_link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dgmall_article',
            },
        ),
    ]
