# Generated by Django 4.1.4 on 2023-01-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgmalldonasi',
            name='master_judul',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dgmalldonasi',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
