# Generated by Django 4.1.3 on 2022-12-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dgmallarticle_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgmallarticle',
            name='kategori',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
