# Generated by Django 4.1.3 on 2022-12-07 05:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dgmallarticle_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dgmallarticle',
            name='kategori',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='title',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
