# Generated by Django 4.1.3 on 2022-12-07 05:27

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dgmallarticle_kategori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgmallarticle',
            name='image_link',
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='content_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
