# Generated by Django 4.1.3 on 2022-12-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dgmallarticle_image_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dgmallarticle',
            name='kategori',
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
