# Generated by Django 4.1.3 on 2022-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_dgmallarticle_kategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgmallarticle',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dgmallarticle',
            name='content_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
