# Generated by Django 4.1.3 on 2022-12-13 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dgmallarticle_image_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DgmallUserArticle',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dgmall_user_article',
            },
        ),
    ]
