# Generated by Django 4.1.3 on 2022-12-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_dgmalluserarticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dgmalluserarticle',
            old_name='username',
            new_name='email',
        ),
    ]
