# Generated by Django 4.1.3 on 2022-12-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_username_dgmalluserarticle_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgmalluserarticle',
            name='token_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
