# Generated by Django 4.1.4 on 2023-01-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dgmalldonasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleDonasi',
        ),
    ]
