# Generated by Django 4.1.4 on 2023-01-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_articledonasi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DgmallDonasi',
            new_name='ArticleDonasi',
        ),
        migrations.AlterModelTable(
            name='articledonasi',
            table='article_donasi',
        ),
    ]
