# Generated by Django 4.1.4 on 2023-01-05 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_dgmalldonasi_articledonasi_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleDonasi',
            new_name='DgmallArticle',
        ),
        migrations.AlterModelTable(
            name='dgmallarticle',
            table='dgmall_donasi',
        ),
    ]
