# Generated by Django 4.1.4 on 2023-01-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_articledonasi_dgmallarticle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DgmallArticle',
        ),
    ]
